# Generated by Django 2.2.6 on 2019-11-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='search_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityApp.SearchTitle'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommunityApp.State'),
        ),
    ]
