# Generated by Django 2.2.6 on 2019-11-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0002_auto_20191113_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(),
        ),
    ]
