# Generated by Django 2.2.6 on 2019-11-13 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0003_auto_20191113_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='search_title_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
