# Generated by Django 2.2.6 on 2019-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityApp', '0004_tweet_search_title_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
